# Generated by Django 5.0.6 on 2024-05-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작성자', models.CharField(max_length=255)),
                ('내용', models.CharField(max_length=255)),
                ('작성일', models.DateTimeField()),
            ],
        ),
    ]
