# Generated by Django 5.0.6 on 2024-05-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
