# Generated by Django 5.0.6 on 2024-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='댓글수',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
