# Generated by Django 5.0.6 on 2024-05-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0005_border_댓글수'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='댓글수',
            field=models.IntegerField(default=0),
        ),
    ]
