# Generated by Django 5.0.6 on 2024-05-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0006_alter_border_댓글수'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='싫어요',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='border',
            name='좋아요',
            field=models.IntegerField(default=0),
        ),
    ]
